# Multi Stage Build

# 1. Build-Umgebung
FROM node:20-alpine AS build

WORKDIR /app

COPY . .

RUN npm ci

RUN npm run build

# 2. Produktionsumgebung

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
